(function(){
'use strict';
var modules=[
['01','Fondations de l’automatisation','Débutant','Comprendre le métier avant les outils.',['Automatisation vs IA','Workflow, trigger et action','Processus métier','Input, output et données','Quand automatiser ?','Cartographier un processus']],
['02','n8n de zéro','Débutant','Construire des workflows propres et testables.',['Interface et nodes','Premier workflow','Données entre nodes','Expressions et mapping','Tests et debugging','Projet : formulaire → CRM']],
['03','Make de zéro','Débutant','Maîtriser scénarios, modules, filtres et erreurs.',['Interface et scénarios','Modules et mapping','Filtres et routers','Scheduling et opérations','Erreurs et reprises','Projet : lead → suivi']],
['04','Technique essentielle','Intermédiaire','API, HTTP, JSON, webhooks, authentification et données.',['API : comprendre une requête','HTTP et méthodes','JSON en pratique','Webhooks','API keys, OAuth et sécurité','Bases de données et CRUD']],
['05','IA générative','Intermédiaire','LLM, prompts, extraction, sorties structurées et évaluation.',['LLM et tokens','Prompt engineering','Contexte et limites','Classification et extraction','Structured outputs','Évaluer une réponse IA']],
['06','Agents IA & systèmes','Avancé','Agents, outils, mémoire, RAG, garde-fous et production.',['Workflow vs agent','Tool calling','Mémoire et contexte','RAG','Guardrails et human-in-the-loop','Production : coût, sécurité, fiabilité']],
['07','Systèmes métier','Avancé','Transformer la technique en solutions concrètes.',['Lead management','Support client','Reporting automatique','Documents et extraction','Rendez-vous et relances','Monitoring et maintenance']],
['08','Trouver une niche','Business','Choisir un terrain par les problèmes, pas par la mode.',['Niche : définition utile','Détecter les douleurs','Évaluer une niche','Interviews et découverte','Choisir son premier terrain','Étude de cas multi-niches']],
['09','Créer son offre','Business','Transformer une compétence en offre claire.',['Résultat vs outil','MVP et démonstration','Audit d’automatisation','Tarification','Proposition commerciale','Livraison et récurrence']],
['10','Prospection & vente','Business','Trouver, contacter, qualifier et convertir.',['Construire une liste','Personnaliser son approche','Email et LinkedIn','Appel découverte','Démo et objections','Closing et suivi']],
['11','Projet client complet','Projet','Construire une solution de A à Z.',['Cadrage','Cartographie','Architecture','Construction V1','Tests et sécurité','Présentation client']],
['12','Évaluation finale','Final','Valider le raisonnement de bout en bout.',['Diagnostic d’entreprise','Choix de solution','Architecture complète','Analyse ROI','Pitch de l’offre','Grand cas final']]
];
function css(){if(document.getElementById('as-v3'))return;var s=document.createElement('style');s.id='as-v3';s.textContent=`
.as-course-body{font-size:16px;line-height:1.78}.as-course-body p{margin:12px 0}.as-boxgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:18px 0}.as-panel{padding:18px;border:1px solid #e4e6ef;border-radius:15px;background:#fff}.as-panel.example{background:#f7faff;border-color:#dce8ff}.as-panel.practice{background:#f5fcf9;border-color:#d8efe7}.as-panel.warning{background:#fff8e8;border-color:#f0d99b}.as-panel.key{background:#faf9ff;border-left:4px solid #6757e8}.as-visual{margin:20px 0;padding:20px;border:1px solid #e4e6ef;border-radius:16px;background:#fafaff}.as-flow{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap}.as-box{padding:12px 14px;background:#eeeaff;border:1px solid #ddd7ff;color:#5546c8;border-radius:11px;font-weight:800}.as-arrow{font-size:21px;color:#6757e8}.as-caption{text-align:center;color:#687087;font-size:13px;margin-top:10px}.as-answer{margin-top:22px;padding:20px;border:1px solid #e4e6ef;border-radius:16px;background:#fbfbfe}.as-answer textarea{width:100%;min-height:160px;border:1px solid #dcdce8;border-radius:12px;padding:12px;resize:vertical}.as-feedback{margin-top:12px;padding:13px;border-radius:11px;display:none}.as-feedback.show{display:block}.as-good{background:#effaf5;color:#147b50}.as-bad{background:#fff1f3;color:#a52d3d}.as-next{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:22px}.as-check{padding:16px;border:1px solid #e4e6ef;border-radius:15px;margin-top:20px;background:#fff}.as-check button{display:block;width:100%;text-align:left;border:1px solid #e4e6ef;background:#fff;border-radius:11px;padding:12px;margin:8px 0}.as-check button.correct{border-color:#15966a;background:#effaf5}.as-check button.wrong{border-color:#d84c5d;background:#fff1f3}@media(max-width:700px){.as-boxgrid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function load(){var s=document.createElement('script');s.src='course-content.js?v=3';s.onload=install;s.onerror=install;document.body.appendChild(s)}
function install(){if(window.__asV3)return;window.__asV3=true;css();window.__AS3={mods:modules};
window.openModule=function(mi){var m=modules[mi],a=document.getElementById('app');a.innerHTML=`<div class="side"><aside class="card toc"><b>${m[0]} · ${m[1]}</b>${m[3].map((x,j)=>`<button onclick="openLesson(${mi},${j})">${j+1}. ${x}</button>`).join('')}</aside><article class="card lesson"><span class="badge">${m[2]}</span><h2>${m[1]}</h2><p class="muted">${m[3].length} leçons · cours détaillés · exemples · pratique · validation</p><div class="grid">${m[3].map((x,j)=>`<div class="card"><span class="pill">Leçon ${j+1}</span><h3>${x}</h3><p class="muted">Cours complet + exemple + exercice + erreurs + validation.</p><button class="btn" onclick="openLesson(${mi},${j})">Commencer</button></div>`).join('')}</div></article></div>`;scrollTo(0,0)};
window.openLesson=function(mi,li){var m=modules[mi],title=m[3][li],c=window.COURSE_CONTENT&&window.COURSE_CONTENT[title],a=document.getElementById('app');if(!c){a.innerHTML='<div class="card"><h2>Contenu en chargement…</h2><p>Actualise la page dans quelques secondes.</p></div>';return}
var visualMap={'Automatisation vs IA':['Règle','Workflow','IA si ambiguïté','Résultat'],'Workflow, trigger et action':['Trigger','Données','Décision','Action','Résultat'],'API : comprendre une requête':['Client','Requête HTTP','API','Réponse'],'Webhooks':['Événement','Webhook','Workflow'],'Tool calling':['Agent','Tool call','Outil','Résultat'],'RAG':['Question','Recherche','Contexte','LLM','Réponse'],'Lead management':['Lead','Qualification','CRM','Commercial'],'Appel découverte':['Prospect','Questions','Diagnostic','Proposition'],'Diagnostic d’entreprise':['Observation','Problème','Priorité','Solution']};
var vv=visualMap[title]?`<div class="as-visual"><div class="as-flow">${visualMap[title].map((x,i)=>`<span class="as-box">${x}</span>${i<visualMap[title].length-1?'<span class="as-arrow">→</span>':''}`).join('')}</div><div class="as-caption">Schéma mental de la notion.</div></div>`:'';
var q=c.quiz?`<div class="as-check"><h3>🧠 Vérifie ta compréhension</h3><p><b>${c.quiz}</b></p><button onclick="this.classList.add('correct');this.nextElementSibling.textContent='✓ '+${JSON.stringify(c.answer)}">Afficher la correction</button><button onclick="this.classList.add('wrong');this.nextElementSibling.textContent='Relis la partie “À retenir”, puis réessaie.'">Je ne sais pas encore</button><div class="feedback"></div></div>`:'';
a.innerHTML=`<div class="side"><aside class="card toc"><b>${m[0]} · ${m[1]}</b>${m[3].map((x,j)=>`<button onclick="openLesson(${mi},${j})" class="${j===li?'active':''}">${j+1}. ${x}</button>`).join('')}</aside><article class="card lesson"><span class="badge">${m[2]} · Leçon ${li+1}/${m[3].length}</span><h2>${title}</h2><div class="as-course-body"><div class="as-panel key"><h3>🎯 Objectif</h3><p>${c.goal}</p></div>${vv}<h3>📖 Cours complet</h3><p>${c.body}</p><div class="as-boxgrid"><div class="as-panel example"><h3>💡 Exemple concret</h3><p>${c.example}</p></div><div class="as-panel practice"><h3>🛠️ Mise en pratique</h3><p>${c.practice}</p></div></div><div class="as-panel key"><h3>🧠 À retenir</h3><p>${c.answer}</p></div><div class="as-panel warning"><h3>⚠️ Erreurs de débutant</h3><p>${c.mistakes}</p></div>${q}</div><div class="as-answer"><h3>✍️ Réponse écrite</h3><p>Explique la notion avec tes propres mots. Cette réponse est un entraînement : pour une correction vraiment pédagogique de ton raisonnement, tu peux aussi me l’envoyer ici.</p><textarea placeholder="Écris ta réponse ici..."></textarea><button class="btn" style="margin-top:10px" onclick="asGrade(this,'${title.replaceAll("'","\\'")}')">Corriger ma réponse</button><div class="as-feedback"></div></div><div class="as-next"><button class="btn secondary" onclick="openModule(${mi})">← Retour au niveau</button>${li<m[3].length-1?`<button class="btn" onclick="openLesson(${mi},${li+1})">Leçon suivante →</button>`:''}</div></article></div>`;scrollTo(0,0)};
window.asGrade=function(btn,title){var c=window.COURSE_CONTENT[title],box=btn.parentElement,ta=box.querySelector('textarea'),fb=box.querySelector('.as-feedback'),v=(ta.value||'').trim();if(!v){fb.className='as-feedback show as-bad';fb.textContent='Écris d’abord ta réponse.';return}var text=(c.body+' '+c.example+' '+c.practice+' '+c.mistakes).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');var words=[...new Set(text.match(/[a-z]{5,}/g)||[])],ans=v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),hits=words.filter(w=>ans.includes(w)).slice(0,15),score=Math.min(10,Math.max(4,Math.round(hits.length/1.6)));fb.className='as-feedback show '+(score>=7?'as-good':'as-bad');fb.innerHTML='<b>Évaluation indicative : '+score+'/10</b><br>'+(score>=7?'Bonne base. Vérifie que tu as expliqué le mécanisme, donné un exemple et mentionné une limite.':'Il manque encore des éléments. Reprends objectif → fonctionnement → exemple → limites, puis réécris ta réponse.')+'<br><small>Le correcteur du site vérifie des éléments textuels ; pour évaluer réellement ton raisonnement, je peux corriger ta réponse ici.</small>'};
document.querySelectorAll('.navlinks button').forEach(function(b){b.addEventListener('click',function(){var p=b.getAttribute('data-p');setTimeout(function(){if(p==='course'){window.__AS3.course();}else if(p==='home'){window.__AS3.home();}},0)})});
window.__AS3.course=function(){var a=document.getElementById('app');a.innerHTML='<section class="hero"><span class="badge" style="background:#ffffff22;color:#fff">PARCOURS COMPLET</span><h1>Automation School</h1><p>12 niveaux · 72 leçons. Chaque leçon est structurée pour apprendre : objectif → cours → exemple → pratique → erreurs → validation.</p></section><div class="grid" style="margin-top:20px">'+modules.map((m,i)=>`<div class="card"><span class="badge">${m[2]}</span><h3>${m[0]} · ${m[1]}</h3><p class="muted">${m[3]}</p><p><b>6 leçons</b> · cours détaillés</p><button class="btn" onclick="openModule(${i})">Ouvrir le niveau</button></div>`).join('')+'</div>';scrollTo(0,0)};
window.__AS3.home=function(){var a=document.getElementById('app');a.innerHTML='<section class="hero"><span class="badge" style="background:#ffffff22;color:#fff">AUTOMATION SCHOOL · V3</span><h1>Apprendre l’automatisation IA comme un vrai métier.</h1><p>Pas seulement des outils : fondations, technique, IA, construction de systèmes, business, prospection et projet client.</p><div class="stats"><div class="stat"><b>12</b><small>niveaux</small></div><div class="stat"><b>72</b><small>leçons</small></div><div class="stat"><b>6</b><small>étapes par leçon</small></div><div class="stat"><b>1</b><small>grand cas final</small></div></div></section><div class="section"><h2>🎯 Commence par le niveau 01</h2><p class="muted">On ne saute pas directement aux agents IA. On construit des bases solides avant de vendre quoi que ce soit.</p><button class="btn" onclick="openModule(0)">Commencer →</button></div>';scrollTo(0,0)};
}
load();
})();