/* Automation School safety renderer + visual helpers. If the main app fails to boot, this file provides a complete fallback UI. */
(function(){
  'use strict';
  var modules = [
    ['01','Fondations','Débutant',['Automatisation vs IA','Workflow, trigger et action','Processus métier','Données : input / output','Quand automatiser ?','Cartographier un processus']],
    ['02','n8n de zéro','Débutant',['Interface et nodes','Premier workflow','Données entre nodes','Expressions et mapping','Tests et debugging','Projet : formulaire → CRM']],
    ['03','Make de zéro','Débutant',['Interface et scénarios','Modules et mapping','Filtres et routers','Scheduling','Erreurs et reprises','Projet : lead → suivi']],
    ['04','Technique essentielle','Intermédiaire',['API','HTTP et méthodes','JSON','Webhooks','API keys et OAuth','Bases de données / CRUD']],
    ['05','IA générative','Intermédiaire',['LLM et tokens','Prompt engineering','Contexte et limites','Classification','Extraction structurée','Évaluer une réponse IA']],
    ['06','Agents IA','Avancé',['Workflow vs agent','Tool calling','Mémoire et contexte','RAG','Guardrails','Coût, sécurité et fiabilité']],
    ['07','Systèmes métier','Avancé',['Lead management','Support client','Reporting','Documents','Rendez-vous et relances','Monitoring et maintenance']],
    ['08','Trouver une niche','Business',['Définir une niche','Détecter les douleurs','Évaluer une niche','Interviews','Choisir son terrain','Études de cas']],
    ['09','Créer son offre','Business',['Résultat vs outil','MVP','Audit d’automatisation','Tarification','Proposition commerciale','Livraison et récurrence']],
    ['10','Prospection & vente','Business',['Construire une liste','Personnaliser son approche','Email et LinkedIn','Appel découverte','Démo et objections','Closing et suivi']],
    ['11','Projet client complet','Projet',['Cadrage','Cartographie','Architecture','Construction V1','Tests et sécurité','Présentation client']],
    ['12','Évaluation finale','Final',['Diagnostic entreprise','Choix de solution','Architecture','ROI','Pitch','Grand cas final']]
  ];
  var lessons = {
    'Automatisation vs IA': '<p><b>Automatisation :</b> une suite de règles exécutées automatiquement. <b>IA :</b> une capacité d’interprétation, génération ou décision probabiliste.</p><div class="concept"><b>Règle pratique :</b> si une règle simple suffit, ne mets pas d’IA inutilement. Utilise l’IA lorsque le problème implique langage, documents, ambiguïté ou classification.</div>',
    'Workflow, trigger et action':'<p>Un workflow décrit une chaîne de traitement. Le <b>trigger</b> le démarre. Les actions transforment les données ou déclenchent quelque chose.</p><div class="visual"><div class="flow"><span class="box">Événement</span><span class="arrow">→</span><span class="box">Données</span><span class="arrow">→</span><span class="box">Traitement</span><span class="arrow">→</span><span class="box">Action</span><span class="arrow">→</span><span class="box">Résultat</span></div></div>',
    'API':'<p>Une API est un contrat qui permet à deux logiciels de communiquer. Tu dois savoir repérer l’endpoint, la méthode HTTP, l’authentification, les paramètres et le format de réponse.</p><div class="visual"><div class="flow"><span class="box">Make / n8n</span><span class="arrow">→ requête</span><span class="box">API</span><span class="arrow">→ réponse</span><span class="box">JSON</span></div></div>',
    'HTTP et méthodes':'<p><b>GET</b> lit généralement, <b>POST</b> crée ou déclenche, <b>PUT/PATCH</b> modifie et <b>DELETE</b> supprime. Les statuts 2xx signalent généralement un succès, 4xx une erreur de requête et 5xx une erreur serveur.</p>',
    'JSON':'<p>JSON est un format de données très utilisé par les API. Tu dois savoir lire objets, tableaux, chaînes, nombres, booléens et valeurs nulles.</p><div class="concept"><code>{"nom":"Emma","budget":1200,"urgent":true}</code></div>',
    'Webhooks':'<p>Un webhook permet à un service d’appeler une URL lorsqu’un événement arrive, au lieu de vérifier périodiquement s’il y a du nouveau.</p><div class="visual"><div class="flow"><span class="box">Événement</span><span class="arrow">→</span><span class="box">Webhook URL</span><span class="arrow">→</span><span class="box">Workflow</span></div></div>',
    'LLM et tokens':'<p>Un LLM traite du texte sous forme de tokens et produit une sortie à partir du contexte fourni. Il faut connaître contexte, fenêtre de contexte, coût, latence, limites et hallucinations.</p>',
    'Prompt engineering':'<p>Un prompt solide précise le rôle, la tâche, le contexte, les contraintes et le format attendu. Pour une automatisation, une sortie structurée est souvent plus fiable qu’un paragraphe libre.</p><div class="concept"><b>Structure :</b> rôle → tâche → contexte → contraintes → format → exemples si nécessaire.</div>',
    'Workflow vs agent':'<p>Un workflow suit une logique conçue à l’avance. Un agent peut choisir des outils et des étapes. L’agent est utile quand le problème est variable, mais il ajoute coût, incertitude et risques.</p><div class="warning"><b>Question réflexe :</b> « Ai-je vraiment besoin que le système décide ? »</div>',
    'Tool calling':'<p>Le tool calling permet à un modèle de demander l’exécution d’une fonction ou d’un outil. Le système exécute ensuite l’action, contrôle le résultat et peut le renvoyer au modèle.</p>',
    'RAG':'<p>Le RAG récupère des informations pertinentes avant la génération. Il est utile pour travailler avec des documents et données métier.</p><div class="visual"><div class="flow"><span class="box">Question</span><span class="arrow">→</span><span class="box">Recherche</span><span class="arrow">→</span><span class="box">Contexte</span><span class="arrow">→</span><span class="box">LLM</span><span class="arrow">→</span><span class="box">Réponse</span></div></div>',
    'Niche : définition utile':'<p>Une niche n’est pas une niche « magique ». C’est un terrain où tu peux comprendre les processus, les douleurs, les décideurs et la capacité à payer. On testera plusieurs marchés avant de choisir.</p>',
    'Résultat vs outil':'<p>Un client n’achète pas « un workflow n8n ». Il achète un résultat : moins de saisie, moins d’oublis, une réponse plus rapide, davantage de leads traités ou un reporting fiable.</p>',
    'Appel découverte':'<p>Avant de vendre, comprends le processus actuel : volume, temps, outils, erreurs, coût, urgence, décisionnaire et résultat souhaité.</p>',
    'Cadrage':'<p>Définis objectif, périmètre, données, outils, utilisateurs, contraintes, critères de réussite et exclusions avant de construire.</p>'
  };
  function css(){ if(document.getElementById('as-safe-style')) return; var s=document.createElement('style');s.id='as-safe-style';s.textContent='.as-safe{margin-top:20px}.as-safe .hero{margin-bottom:24px}.as-safe .card{padding:20px}.as-safe .flow{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap}.as-safe .box{padding:11px 13px;background:#eeeaff;border:1px solid #ddd7ff;color:#5546c8;border-radius:11px;font-weight:800}.as-safe .arrow{font-size:21px;color:#6757e8}.as-safe .visual{margin:18px 0;padding:18px;border:1px solid #e4e6ef;border-radius:16px;background:#fafaff}.as-safe .concept{background:#faf9ff;border:1px solid #dfdbff;border-left:4px solid #6757e8;padding:15px;border-radius:12px}.as-safe .warning{background:#fff8e8;border:1px solid #f0d99b;padding:15px;border-radius:12px}.as-safe .option{display:block;width:100%;text-align:left;border:1px solid #e4e6ef;background:white;border-radius:11px;padding:11px;margin:7px 0}.as-safe textarea{width:100%;min-height:130px;border:1px solid #e4e6ef;border-radius:11px;padding:12px}.as-safe .feedback{margin-top:10px;padding:12px;border-radius:10px}.as-safe .good{background:#effaf5;color:#147b50}.as-safe .bad{background:#fff1f3;color:#a52d3d}.as-safe .lesson-list button{margin:4px 5px 4px 0}.as-safe .back{margin-bottom:15px}';document.head.appendChild(s);}
  function app(){return document.getElementById('app');}
  function setNav(active){document.querySelectorAll('.navlinks button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-p')===active);});}
  function home(){setNav('home');app().innerHTML='<div class="as-safe"><section class="hero"><span class="badge" style="background:#ffffff22;color:#fff">AUTOMATION SCHOOL</span><h1>Apprendre l’automatisation IA de zéro jusqu’au business.</h1><p>Un parcours progressif : fondations → n8n → Make → API → IA → agents → systèmes métier → niche → offre → prospection → projet client.</p><div class="bar"><i style="width:0%"></i></div><p>0% · Commence par le Niveau 01.</p></section><div class="grid"><div class="card"><h3>📚 Cours</h3><p class="muted">Théorie, exemples, schémas, erreurs de débutant et exercices.</p></div><div class="card"><h3>🧠 Validation</h3><p class="muted">QCM, réponses écrites et cas pratiques.</p></div><div class="card"><h3>💼 Business</h3><p class="muted">Niche, offre, prospection, vente, livraison et récurrence.</p></div></div><div class="section"><h2>Commencer</h2><p class="muted">Le parcours se fait dans l’ordre. Ne saute pas directement aux agents IA.</p><button class="btn" onclick="AS.course()">Commencer le Niveau 01 →</button></div></div>';}
  function course(){setNav('course');var h='<div class="as-safe"><h2>Parcours A → Z</h2><p class="muted">12 niveaux · 72 leçons. Avance dans l’ordre.</p><div class="grid">';modules.forEach(function(m,i){h+='<div class="card"><span class="badge">'+m[2]+'</span><h3>'+m[0]+' · '+m[1]+'</h3><p class="muted">'+m[3]+'</p><p>'+m[3]+'</p><button class="btn" onclick="AS.module('+i+')">Ouvrir le niveau</button></div>';});h+='</div></div>';app().innerHTML=h;}
  function module(i){setNav('course');var m=modules[i],h='<div class="as-safe"><button class="btn secondary back" onclick="AS.course()">← Parcours</button><span class="badge">Niveau '+m[0]+' · '+m[2]+'</span><h2>'+m[1]+'</h2><p class="muted">Progression volontairement graduelle.</p><div class="grid lesson-list">';m[3].forEach(function(t,j){h+='<div class="card"><span class="pill">Leçon '+(j+1)+'</span><h3>'+t+'</h3><button class="btn" onclick="AS.lesson('+i+','+j+')">Commencer</button></div>';});h+='</div></div>';app().innerHTML=h;}
  function lesson(mi,li){setNav('course');var m=modules[mi],title=m[3][li],body=lessons[title]||'<p>Cette leçon développe <b>'+title+'</b> dans le contexte de l’automatisation IA.</p><div class="concept"><b>Objectif :</b> comprendre la notion, savoir l’expliquer simplement, reconnaître quand l’utiliser et l’appliquer dans un workflow.</div><h3>À retenir</h3><p>Pars toujours du problème métier. Identifie les entrées, les règles, les exceptions, les actions et le résultat avant de choisir un outil.</p><h3>Exercice</h3><p>Imagine une entreprise qui réalise cette tâche chaque semaine. Décris comment tu pourrais l’améliorer et pourquoi.</p>';app().innerHTML='<div class="as-safe"><button class="btn secondary back" onclick="AS.module('+mi+')">← Retour au niveau</button><article class="card"><span class="badge">'+m[2]+' · Leçon '+(li+1)+'</span><h2>'+title+'</h2><h3>🎯 Objectif</h3><p>À la fin de la leçon, tu dois pouvoir expliquer cette notion avec tes propres mots et l’utiliser dans un cas concret.</p>'+body+'<h3>🧠 Vérifie ta compréhension</h3><div class="card"><p><b>Quelle est la meilleure façon d’apprendre cette notion ?</b></p><button class="option" onclick="this.classList.add(\'good\');this.nextElementSibling.classList.add(\'bad\');document.getElementById(\'fb\').textContent=\'✓ Exact : comprendre, pratiquer puis valider.\'">Comprendre → pratiquer → valider</button><button class="option" onclick="this.classList.add(\'bad\');document.getElementById(\'fb\').textContent=\'Pas exactement : ne te contente pas de regarder des tutoriels.\'">Regarder beaucoup de tutoriels</button><div id="fb" class="feedback"></div></div><div class="card" style="margin-top:15px"><h3>✍️ Réponse écrite</h3><p>Écris avec tes propres mots ce que tu retiens de cette leçon.</p><textarea id="answer" placeholder="Ta réponse..."></textarea><button class="btn" style="margin-top:9px" onclick="AS.grade()">Corriger</button><div id="grade" class="feedback"></div></div></article></div>';}
  function practice(){setNav('practice');app().innerHTML='<div class="as-safe"><h2>🧪 Laboratoire pratique</h2><p class="muted">Des missions pour passer de la théorie à la construction.</p><div class="grid"><div class="card"><h3>Mission 1 · Workflow papier</h3><p>Choisis une tâche répétitive et écris : trigger → données → traitement → action → résultat.</p></div><div class="card"><h3>Mission 2 · Détective API</h3><p>Repère endpoint, méthode, authentification et réponse JSON dans une documentation API.</p></div><div class="card"><h3>Mission 3 · Décision IA</h3><p>Choisis cinq tâches et décide : règle, IA ou humain. Justifie.</p></div><div class="card"><h3>Mission 4 · Mini-audit</h3><p>Identifie trois processus d’une entreprise qui pourraient être améliorés.</p></div></div></div>';}
  function business(){setNav('business');app().innerHTML='<div class="as-safe"><h2>💼 Business Lab</h2><p class="muted">Le but n’est pas de vendre « de l’IA », mais une amélioration mesurable.</p><div class="grid"><div class="card"><h3>1. Niche</h3><p>Volume, douleur, fréquence, pouvoir d’achat, accès au décideur.</p></div><div class="card"><h3>2. Problème</h3><p>Temps perdu, erreurs, leads oubliés, délais, reporting manuel.</p></div><div class="card"><h3>3. Offre</h3><p>Résultat attendu, périmètre, MVP, prix, maintenance.</p></div><div class="card"><h3>4. Prospection</h3><p>Recherche → personnalisation → audit → démo → appel → proposition.</p></div><div class="card"><h3>5. Livraison</h3><p>Cadrage, construction, tests, sécurité, documentation et suivi.</p></div><div class="card"><h3>6. Récurrence</h3><p>Monitoring, maintenance, optimisation et nouvelles automatisations.</p></div></div></div>';}
  function glossary(){setNav('glossary');var terms=[['API','Communication entre logiciels.'],['Webhook','Appel envoyé lorsqu’un événement survient.'],['JSON','Format structuré de données.'],['Trigger','Événement qui démarre un workflow.'],['Node','Étape d’un workflow n8n.'],['LLM','Modèle de langage.'],['Prompt','Instruction et contexte donnés au modèle.'],['Agent IA','Système capable d’utiliser un modèle et des outils.'],['RAG','Recherche de données avant génération.'],['Tool calling','Demande d’exécution d’un outil par le modèle.'],['CRM','Outil de gestion des prospects et clients.'],['OAuth','Mécanisme d’autorisation déléguée.'],['CRUD','Créer, lire, modifier, supprimer.'],['MVP','Version minimale pour tester une solution.'],['ROI','Retour sur investissement.']];app().innerHTML='<div class="as-safe"><h2>📖 Glossaire</h2><div class="grid">'+terms.map(function(t){return '<div class="card"><b>'+t[0]+'</b><p class="muted">'+t[1]+'</p></div>';}).join('')+'</div></div>';}
  function resources(){setNav('resources');app().innerHTML='<div class="as-safe"><h2>🔗 Ressources</h2><div class="grid"><div class="card"><h3>Make Academy</h3><p>Formation officielle pour les concepts et l’outil Make.</p><a class="btn" href="https://academy.make.com/" target="_blank">Ouvrir</a></div><div class="card"><h3>Documentation n8n</h3><p>Référence technique officielle.</p><a class="btn" href="https://docs.n8n.io/" target="_blank">Ouvrir</a></div></div></div>';}
  window.AS={home:home,course:course,module:module,lesson:lesson,practice:practice,business:business,glossary:glossary,resources:resources,grade:function(){var v=(document.getElementById('answer').value||'').trim(),g=document.getElementById('grade');if(!v){g.textContent='Écris une réponse avant de corriger.';g.className='feedback bad';return;}g.textContent='✓ Bonne démarche : ta réponse est enregistrée pour être discutée et corrigée plus finement avec le formateur.';g.className='feedback good';}};
  function boot(){css();document.querySelectorAll('.navlinks button').forEach(function(b){b.onclick=function(){var p=b.getAttribute('data-p');if(AS[p])AS[p]();};});var a=app();if(!a)return;if(!a.textContent.trim()){home();}}
  setTimeout(boot,80);
})();